#Talar om för bundler var biblioteken vi ska använda finns
#kör "bundle install" i terminalen i samma mapp för att ladda ner biblioteken

source 'https://rubygems.org'

gem 'rack'
gem 'rackup'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rerun'
gem 'sqlite3'
gem 'cells'
gem 'cells-erb'
gem 'activesupport'
gem 'sinatra-r18n'
gem 'kramdown'
gem 'rack-throttle'
# gem 'rack-ssl-enforcer'
# gem 'secure_headers'
gem 'sanitize'
# gem 'rack-protection'
gem 'bcrypt'
gem 'dotenv'
gem 'sendgrid-ruby'
gem 'sinatra-validation'
gem 'valid_email', require: 'valid_email/validate_email'